resources:
  - name: sources
    type: git
    source:
      uri: https://github.com/joris77/admin-web.git
      branch: master
  - name: admin-web-image
    type: docker-image
    source:
      repository: smartworkx/admin-web
      email: {{docker_mail}}
      username: {{docker_user}}
      password: {{docker_pass}}

jobs:
- name: build
  plan:
  - get: sources
    trigger: true
  - task: dist
    file: sources/pipeline/dist.yml
  - task: prepare-build
    file: sources/pipeline/prepare-build.yml
  - put: admin-web-image
    params: {build: build, tag: build/tag}
- name: deploy-staging
  plan:
  - get: admin-web-image
    trigger: false
  - get: sources
    trigger: false
  - task: deploy
    file: sources/pipeline/deploy.yml

