apiVersion: v1
kind: Service
metadata:
  name: admin-web
  labels:
    app: admin-web
    visualize: "true"
    name: "admin-web"
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: admin-web
  type: "NodePort"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: admin-web
spec:
  replicas: 1
  revisionHistoryLimit: 2
  minReadySeconds: 20
  template:
    metadata:
      labels:
        app: admin-web
        visualize: "true"
        name: "admin-web"
    spec:
      containers:
      - name: admin-web
        image: smartworkx/admin-web:ADMIN_WEB_IMAGE_TAG
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
